---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-vpc
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 8531b562-91d5-4974-a195-5dff72ef2a5d
    include_git_submodules: true
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
